/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productcrud;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author minhle
 */
public class product extends javax.swing.JFrame {

      /**
       * Creates new form product
       */
      public product() {
            initComponents();
            Connect();
            LoadProductNo();
      }

      Connection con;
      PreparedStatement pst;
      ResultSet rs;

      public void Connect() {
            try {
                  Class.forName("com.mysql.cj.jdbc.Driver");
                  con = DriverManager.getConnection("jdbc:mysql://localhost:3308/productInformation", "root", "");
            } catch (ClassNotFoundException ex) {
                  Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                  Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
            }
      }

      public void LoadProductNo() {
            try {
                  pst = con.prepareStatement("select id from product");
                  rs = pst.executeQuery();
                  txtpid.removeAllItems();

                  while (rs.next()) {
                        txtpid.addItem(rs.getString(1));
                  }

            } catch (SQLException ex) {
                  Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
            }
      }

      /**
       * This method is called from within the constructor to initialize the form.
       * WARNING: Do NOT modify this code. The content of this method is always
       * regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated
      // Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            txtpname = new javax.swing.JTextField();
            txtprice = new javax.swing.JTextField();
            txtqty = new javax.swing.JTextField();
            jLabel5 = new javax.swing.JLabel();
            txtpid = new javax.swing.JComboBox<>();
            jButton4 = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();
            jPanel2 = new javax.swing.JPanel();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();
            jPanel3 = new javax.swing.JPanel();
            jLabel6 = new javax.swing.JLabel();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            jLabel9 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Product Information"));

            jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
            jLabel2.setText("Name");

            jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
            jLabel3.setText("Price");

            jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
            jLabel4.setText("Quantity");

            txtprice.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        txtpriceActionPerformed(evt);
                  }
            });

            jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
            jLabel5.setText("Product ID");

            jButton4.setText("Search");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton4ActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(jPanel1Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup().addGap(46, 46, 46).addGroup(
                                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2).addComponent(jLabel3).addComponent(jLabel4))
                                    .addGap(55, 55, 55)
                                    .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtpname).addComponent(txtprice).addComponent(txtqty,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(84, 84, 84)
                                                            .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtpid,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                    177,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel5,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                    97,
                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup().addGap(123, 123, 123)
                                                            .addComponent(jButton4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 105,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
            jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup().addGap(19, 19, 19).addGroup(jPanel1Layout
                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
                                                            .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel2)
                                                            .addComponent(txtpname,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(txtpid,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(6, 6, 6))
                                                .addGroup(jPanel1Layout
                                                            .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel3).addComponent(txtprice,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton4).addGap(10, 10, 10))
                                    .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel4).addComponent(txtqty,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addContainerGap(54, Short.MAX_VALUE)));

            jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
            jLabel1.setText("Inventory Management System");

            jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Control Panel"));

            jButton1.setText("Add");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                  }
            });

            jButton2.setText("Update");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                  }
            });

            jButton3.setText("Delete");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton3ActionPerformed(evt);
                  }
            });

            jButton5.setText("Reset");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton5ActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout
                        .setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup().addGap(33, 33, 33)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(84, 84, 84)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(79, 79, 79)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(83, 83, 83)
                                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                            javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(82, Short.MAX_VALUE)));
            jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup().addGap(7, 7, 7)
                                    .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton3).addComponent(jButton5))
                                    .addContainerGap()));

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact"));

            jLabel6.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
            jLabel6.setText("Ⓒ 2021 Minh Le & 3T Holdings All Rights Reserved");

            jLabel7.setText("Phone: +1 (781) 475 - 3633");

            jLabel8.setText("Email: minhle.cfo@tttholdings.com");

            jLabel9.setText("Address: 1686 Massachusetts Avenue, Cambridge, MA 02138");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(jPanel3Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9).addComponent(jLabel8).addComponent(jLabel7)
                                                .addComponent(jLabel6))
                                    .addGap(19, 19, 19)));
            jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9).addContainerGap(22, Short.MAX_VALUE)));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGroup(layout
                                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup().addGap(29, 29, 29).addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                            javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup().addGap(230, 230, 230)
                                                .addComponent(jLabel1)))
                                    .addContainerGap(24, Short.MAX_VALUE)));
            layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(20, 20, 20).addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(40, Short.MAX_VALUE)));

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtpriceActionPerformed
            // TODO add your handling code here:
      }// GEN-LAST:event_txtpriceActionPerformed

      private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
            // TODO add your handling code here:
            try {
                  // TODO add your handling code here:

                  String pid = txtpid.getSelectedItem().toString();

                  pst = con.prepareStatement("select * from product where id = ?");
                  pst.setString(1, pid);
                  rs = pst.executeQuery();

                  if (rs.next()) {
                        txtpname.setText(rs.getString(2));
                        txtprice.setText(rs.getString(3));
                        txtqty.setText(rs.getString(4));
                  }

            } catch (SQLException ex) {
                  Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
            }
      }// GEN-LAST:event_jButton4ActionPerformed

      private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
            try {
                  String pname = txtpname.getText();
                  String price = txtprice.getText();
                  String qty = txtqty.getText();

                  pst = con.prepareStatement("insert into product (pname, price, qty) values(?,?,?)");
                  pst.setString(1, pname);
                  pst.setString(2, price);
                  pst.setString(3, qty);
                  int k = pst.executeUpdate();

                  if (k == 1) {
                        JOptionPane.showMessageDialog(this, "Successfully Added");
                        txtpname.setText("");
                        txtprice.setText("");
                        txtqty.setText("");
                        txtpname.requestFocus();
                        LoadProductNo();
                  } else {
                        JOptionPane.showMessageDialog(this, "Fail to Add");
                  }
            } catch (SQLException ex) {
                  Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
            }
      }// GEN-LAST:event_jButton1ActionPerformed

      private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
            try {
                  String pname = txtpname.getText();
                  String price = txtprice.getText();
                  String qty = txtqty.getText();
                  String pid = txtpid.getSelectedItem().toString();
                  pst = con.prepareStatement("update product set pname = ?, price = ?, qty = ? where id = ?");
                  pst.setString(1, pname);
                  pst.setString(2, price);
                  pst.setString(3, qty);
                  pst.setString(4, pid);
                  int k = pst.executeUpdate();

                  if (k == 1) {
                        JOptionPane.showMessageDialog(this, "Record Updated");
                        txtpname.setText("");
                        txtprice.setText("");
                        txtqty.setText("");
                        txtpname.requestFocus();
                        LoadProductNo();
                  } else {
                        JOptionPane.showMessageDialog(this, "Fail to Update");
                  }
            } catch (SQLException ex) {
                  Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
            }
      }// GEN-LAST:event_jButton2ActionPerformed

      private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
            // TODO add your handling code here:
            txtpname.setText("");
            txtprice.setText("");
            txtqty.setText("");
            txtpname.requestFocus();
            LoadProductNo();
      }// GEN-LAST:event_jButton5ActionPerformed

      private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
            // TODO add your handling code here:
            try {
                  String pid = txtpid.getSelectedItem().toString();
                  pst = con.prepareStatement("delete from product where id = ?");
                  pst.setString(1, pid);
                  int k = pst.executeUpdate();

                  if (k == 1) {
                        JOptionPane.showMessageDialog(this, "Record Deleted");
                        txtpname.setText("");
                        txtprice.setText("");
                        txtqty.setText("");
                        txtpname.requestFocus();
                        LoadProductNo();
                  } else {
                        JOptionPane.showMessageDialog(this, "Fail to Delete");
                  }
            } catch (SQLException ex) {
                  Logger.getLogger(product.class.getName()).log(Level.SEVERE, null, ex);
            }
      }// GEN-LAST:event_jButton3ActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
            // (optional) ">
            /*
             * If Nimbus (introduced in Java SE 6) is not available, stay with the default
             * look and feel. For details see
             * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Metal".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null,
                              ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null,
                              ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null,
                              ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null,
                              ex);
            }
            // </editor-fold>
            // </editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new product().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton jButton1;
      private javax.swing.JButton jButton2;
      private javax.swing.JButton jButton3;
      private javax.swing.JButton jButton4;
      private javax.swing.JButton jButton5;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabel8;
      private javax.swing.JLabel jLabel9;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel2;
      private javax.swing.JPanel jPanel3;
      private javax.swing.JComboBox<String> txtpid;
      private javax.swing.JTextField txtpname;
      private javax.swing.JTextField txtprice;
      private javax.swing.JTextField txtqty;
      // End of variables declaration//GEN-END:variables
}
